service: synergy

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  timeout: 300
  memorySize: 1536

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::ez-react-boilerplate/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: githook
          method: post
#    Define function environment variables here
#    environment:
#      variable2: value2

resources:
  Resources:
    websiteBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ez-react-boilerplate
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
    websiteBucketPolicy:
      Type: "AWS::S3::BucketPolicy"
      Properties:
        Bucket: ez-react-boilerplate
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: "arn:aws:s3:::ez-react-boilerplate/*"